### ISSUE TITLE
install

### ISSUE THREAD

**Issue by AMaynard10** [ChenWeiyan/LandSCENT#1]
Hello, maybe I missed it but how do you install the package?

**Comment by AMaynard10** [comment]
`library(devtools)`
`install_github("ChenWeiyan/LandSCENT")`

The above worked for install, however there is a dependent package error: 

No methods found in package ‘DelayedArray’ for request: ‘write_block_to_sink’ when loading ‘DelayedMatrixStats’

I tried then to install the package alone and found the package is not available for R 3.5.0. 

> install.packages("DelayedArray")
package ‘DelayedArray’ is not available (for R version 3.5.0)

**Comment by ChenWeiyan** [comment]
Hello,

I think it is about the installation of package `DelayedArray`. Since `DelayedArray` is a Bioconductor package, `install_github` may not correctly install it before loading `DelayedMatrixStats`.

The proper way to install it is the following:

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("DelayedArray")
```

Another way may solve the problem is, run the following before install `LandSCENT`:

```
BiocManager::install(c("DelayedArray", "scater", "cluster", "corpcor", "igraph", "isva", "mclust", "parallel", "stats", "grDevices", "graphics", "marray", "scater", "Biobase", "SingleCellExperiment", "Rtsne", "irlba", "plot3D", "MASS", "dbscan", "monocle", "DelayedArray", "Matrix"))
```

In case you get other packages which are not well installed.

BTW, I recommend using `BiocManager:install` to install packages, which can deal with packages both from CRAN and Bioconductor.

Hope this be helpful!

**Comment by AMaynard10** [comment]
Thank you. Everything is installed and I'm running through the demo. Thanks so much for the quick response 👍
