### ISSUE TITLE
Error at the InferLandmark() step

### ISSUE THREAD

**Issue by aditisk** [ChenWeiyan/LandSCENT#10]
Hi @ChenWeiyan, thanks for the great package. I am following the tutorial and I'm getting at error message at the InferLandmark() step. The error is as follows:

InferLandmark.o <- InferLandmark(InferPotency.o, pheno.v = data.sce$orig.ident, reduceMethod = "PCA", clusterMethod = "PAM",k_pam = 2)
[1] "Now estimating number of significant components of variation in scRNA-Seq data"
[1] "Centering and scaling matrix"
[1] "Done, now performing SVD"
[1] "Performing full SVD since dimensionality of data matrix is not big"
[1] "Done"
[1] "Number of significant components = 1"
[1] "Do dimension reduction via PCA"
Error in svd.o$v[, 1:2] : subscript out of bounds

How can I fix this ? Thanks in advance for your help.

**Comment by ChenWeiyan** [comment]
Hi,

It seems the output `Number of significant components = 1` which indicated the error.

This means there probably be some problems with the input matrix, you may need to check the data matrix to see if there anything strange.

Best,
Weiyan

**Comment by aditisk** [comment]
Hi @ChenWeiyan,

Thanks for getting back to me. I couldn’t find missing values or anything else odd in the matrix. Is there anything specific I should be looking for ? Could the small number of cells be an issue ? This is a published dataset and has around 3k cells for 1 sample and 1.5k for the other.

**Comment by ChenWeiyan** [comment]
Hi,

The number of cells is fine.

The estimation of `Number of significant components` is based on a random matrix theory, which works with your input matrix. Since the `Number of significant components = 1`, it means your data matrix has already been transformed or similar operation.

So you may need to check the matrix stored in `InferPotency.o $expMC`. Make sure it has the correct information of the integrated data, eg. the correct dimension or expr information.

And also important to check if the SR values are all correctly calculated.

Hope this be helpful.

Best,
Weiyan

**Comment by aditisk** [comment]
Hi,

I was using a transformed matrix which was probably the reason for the error. Before I move forward, I wanted to clarify if a mouse dataset can be used ?

Thanks.

**Comment by ChenWeiyan** [comment]
Hi,

Yes, of course. Just remember to make sure the gene identifier is the same with the PPI network. Say if you are using the PPI network in our package, you need to get the homolog gene with human and transfer to EntrezID.

Best,
Weiyan

**Comment by aditisk** [comment]
@ChenWeiyan I'll close this issue for now since I won't be working on this project right away. I'll reopen if I still have issues. Thanks for your help.
