### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub:   Line starting 'Lice ...' is malformed!

### ISSUE THREAD

**Issue by naraw58** [ChenWeiyan/LandSCENT#12]
I try several times to install the package on R or Studio but i couldn't. In RStudio
Version 1.3.1093 and R 4.0.3 
The i try to install it by downloading the zip file and install from file but unfortunately give me below error :
 error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'excess_pi_covid-master/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

please show me a simple way to use the package
Thanks

**Comment by ChenWeiyan** [comment]
Hi,

Thanks for trying out my package!

Considering the ERROR `Error in install.packages : cannot open the connection`, it seems the problem is from your side. Could be network connection error etc.

You may find useful suggestion from the link below:
https://community.rstudio.com/t/unable-to-install-package-in-r-studio/15930

And from the warning message `cannot open compressed file 'excess_pi_covid-master/DESCRIPTION', probable reason 'No such file or directory'`, you may not be installing the correct package. It seem you are trying to install something from `excess_pi_covid`. You could check again and make sure you are installing `LandSCENT` from my repo.

A quick installation guide:

`Open up R/RStudio`
`install.packages("devtools")`
`devtools::install_github("ChenWeiyan/LandSCENT")`

Best,
Weiyan

**Comment by naraw58** [comment]
Thank you very much
