### ISSUE TITLE
Seurat object how to switch to a singlecellexperiment matrix to use LandSCENT?and I wonder the time about running time in 10000 cells conditions?

### ISSUE THREAD

**Issue by Peiyuan1214** [ChenWeiyan/LandSCENT#17]
Seurat object how to switch to a singlecellexperiment matrix to use LandSCENT?and I wonder the time about running time in 10000 cells conditions? THANKS

**Comment by ChenWeiyan** [comment]
For data type conversion, you can check Seurat official page or https://satijalab.org/seurat/articles/conversion_vignette.html if it is available. But I recommend to use the count matrix itself as an input since LandSCENT didn't incorporate Seurat or sce format.

As for the running time, 10k cells would take LandSCENT more than 10 hrs using only 1 Intel Xeon core.
