### ISSUE TITLE
Error: Failed to install 'unknown package' from GitHub

### ISSUE THREAD

**Issue by 3Ricoo** [ChenWeiyan/LandSCENT#7]
Hi,

I am trying to install LandSCENT  via `if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")
devtools::install_github("ChenWeiyan/LandSCENT")`
But I met this error:
`Error: Failed to install 'unknown package' from GitHub:
  Failed to connect to api.github.com port 443: Connection refused`

Here are my sessionInfo():
`R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS  10.15.3

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] C/UTF-8/C/C/C/C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.2.2 usethis_1.5.1 

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        magrittr_1.5      uuid_0.1-4        pkgload_1.0.2    
 [5] R6_2.4.0          rlang_0.4.5       tools_3.6.0       pkgbuild_1.0.6   
 [9] sessioninfo_1.1.1 cli_1.1.0         withr_2.1.2       htmltools_0.4.0  
[13] ellipsis_0.3.0    remotes_2.1.1     assertthat_0.2.1  digest_0.6.25    
[17] rprojroot_1.3-2   crayon_1.3.4      processx_3.4.2    IRdisplay_0.7.0  
[21] repr_1.1.0        callr_3.4.2       base64enc_0.1-3   fs_1.3.1         
[25] ps_1.3.2          IRkernel_1.1      curl_4.3          testthat_2.3.2   
[29] evaluate_0.14     memoise_1.1.0     glue_1.3.1        pbdZMQ_0.3-3     
[33] pillar_1.4.2      compiler_3.6.0    desc_1.2.0        backports_1.1.4  
[37] prettyunits_1.1.1 jsonlite_1.6.1 `

**Comment by ChenWeiyan** [comment]
Hi,

According to the 433 Error, it is actually a connection error with your local equipment/server.

You need to update the Git Config for proxy setting so that you can access GitHub then.

I attached several links below (from both Chinese & English Q&A community):

1.https://blog.csdn.net/Hodors/article/details/103226958
2.https://stackoverflow.com/questions/18356502/github-failed-to-connect-to-github-443-windows-failed-to-connect-to-github
3.https://github.com/npm/npm/issues/10037

Hope this solve your problem.

Best,
Weiyan

**Comment by 3Ricoo** [comment]
thanks for your advice,  via changing proxy and Chinese mirror I did download some supported package from CRAN.  But there is an error I cannot fix it when I run `devtools::install_github("ChenWeiyan/LandSCENT")`
Indeed, I could update 106 packages from CRAN. However, when I am going to ''make'' steps, the error is as follows:
`In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:655:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/gethostuuid.h:39:17: error: unknown type name 'uuid_t'
int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_NA);
                ^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:662:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int      getsgroups_np(int *, uuid_t);
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:664:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int      getwgroups_np(int *, uuid_t);
                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:727:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int      setsgroups_np(int, const uuid_t);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:729:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int      setwgroups_np(int, const uuid_t);
                                  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t        uid_t;
                              ^
5 errors generated.
make: *** [/Users/eric/anaconda3/envs/rBio/lib/R/etc/Makeconf:176: annoy.o] Error 1
ERROR: compilation failed for package ‘RcppAnnoy’
* removing ‘/Users/eric/anaconda3/envs/rBio/lib/R/library/RcppAnnoy’
Error: Failed to install 'LandSCENT' from GitHub:
  (converted from warning) installation of package ‘RcppAnnoy’ had non-zero exit status`

Best,

Eric

**Comment by 3Ricoo** [comment]
Thanks for your advice, via changing proxy and Chinese mirror I did download some supported package from CRAN. But there is an error I cannot fix it when I run `devtools::install_github("ChenWeiyan/LandSCENT")`
Indeed, I could update 106 packages from CRAN. However, when I am going to ''make'' steps, the error is as follows:
`In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:655:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/gethostuuid.h:39:17: error: unknown type name 'uuid_t'
int gethostuuid(uuid_t, const struct timespec *) __OSX_AVAILABLE_STARTING(__MAC_10_5, __IPHONE_NA);
^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:662:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int getsgroups_np(int *, uuid_t);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t uid_t;
^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:664:27: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int getwgroups_np(int *, uuid_t);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t uid_t;
^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:727:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int setsgroups_np(int, const uuid_t);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t uid_t;
^
In file included from annoy.cpp:39:
In file included from ../inst/include/annoylib.h:22:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/unistd.h:729:31: error: unknown type name 'uuid_t'; did you mean 'uid_t'?
int setwgroups_np(int, const uuid_t);
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_uid_t.h:31:31: note: 'uid_t' declared here
typedef __darwin_uid_t uid_t;
^
5 errors generated.
make: *** [/Users/eric/anaconda3/envs/rBio/lib/R/etc/Makeconf:176: annoy.o] Error 1
ERROR: compilation failed for package ‘RcppAnnoy’

removing ‘/Users/eric/anaconda3/envs/rBio/lib/R/library/RcppAnnoy’
Error: Failed to install 'LandSCENT' from GitHub:
(converted from warning) installation of package ‘RcppAnnoy’ had non-zero exit status`

Best,

Eric

**Comment by 3Ricoo** [comment]
Apparently, I can barely search anything about  RcppAnnoy on Google.

**Comment by ChenWeiyan** [comment]
Hi Eric,

Obviously it is an error from the installation of package "RcppAnnoy". And it seems to be some conflicts between RcppAnnoy library and the MacOS system library.

I just tried to installed "RcppAnnoy" on my MacBook Pro 2017 13' and it works, so I could not replay the error. But I could give some information:
1. My system is macOS Catalina version 10.15.4
2. I used RStudio under R version 3.6.0 and install the package from binary source
3. I attached the source binary .tgz file I used so that you can try on your Mac

And I searched on Google with "RcppAnnoy macOS error", there seems to be some similar cases happened in other packages, like "Seurat". The following are some related links:

https://www.google.com/urlsa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=2ahUKEwiItanvhr_oAhUET98KHcm8A6oQFjAAegQIBhAB&url=https%3A%2F%2Fgithub.com%2Feddelbuettel%2Frcppannoy%2Fissues%2F46&usg=AOvVaw21i81SryTEizddAlC2bIQf

https://www.google.com/urlsa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwiItanvhr_oAhUET98KHcm8A6oQFjABegQIAhAB&url=https%3A%2F%2Fgithub.com%2Fsatijalab%2Fseurat%2Fissues%2F2275&usg=AOvVaw3nGIaIdAJp3XRslRF4IBiT

https://www.google.com/urlsa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=2ahUKEwiItanvhr_oAhUET98KHcm8A6oQFjACegQIBBAB&url=https%3A%2F%2Fcommunity.rstudio.com%2Ft%2Ferror-trying-to-install-seurat-package-on-macos%2F58283&usg=AOvVaw3LYGwqx9w-hoa8munkqmIQ

Hope this could be helpful!

Best,
Weiyan

**Comment by ChenWeiyan** [comment]
Since the comment does not support .tgz file, I compressed it again.

[RcppAnnoy_0.0.16.tgz.zip](https://github.com/ChenWeiyan/LandSCENT/files/4398412/RcppAnnoy_0.0.16.tgz.zip)

**Comment by 3Ricoo** [comment]
I am appreciated your timely support, I tried to download RcppAnnoy directly and install from the local document.  Unfortunately, the same error came, which means the error occurred in the installation step.

As you suggest, searching with "RcppAnnoy macOS error" on google did show some same problem, especially [Error trying to install Seurat Package on MacOS](https://community.rstudio.com/t/error-trying-to-install-seurat-package-on-macos/58283).

Besides, I have no idea that I cannot open the url you provided somehow.(I can google yet)

**Comment by ChenWeiyan** [comment]
OK. Then I probably cannot provide further suggestion, since I am not expert with MacOS. But I think the error mostly came along with the system. Hope the similar cases can give you some clues.

And sorry about the urls. My network is kind of unstable recently and I have no access to Google right now :( So the urls may be affected by my poor connection.

**Comment by 3Ricoo** [comment]
Thanks a lot anyway, I'll keep an eye on the error issue and may install Landscape in Linux back to campus.
