### ISSUE TITLE
Comparison between different Data sets

### ISSUE THREAD

**Issue by danhtruong** [ChenWeiyan/LandSCENT#9]
Hi,

Thank you for the amazing tool. I have found great results with it so far. I wish to compare the SR values with different datasets.

Do I need to combine dataset A and B into a single object and then perform analysis? Or do I keep them separately and only need to compare the resulting normalized SR/MaxSR from either dataset? 

Is the MaxSR specific to the analysis for a single dataset?

Thanks,
Danh

**Comment by ChenWeiyan** [comment]
Hi Danh,

Thanks for using our package!

MaxSR is specific to the dataset since it is derived from the integrated network topology. And the integrated network would vary from dataset to dataset.

The output SR values have already been normalized, so typically the MaxSR does not help with the analysis, unless you are trying to investigate the network topology change in case/control study etc.

As for the combination of dataset, if the separate datasets are from the same/similar lineages, you could try to use an integrated dataset to calculate new SR values.
But for datasets reflecting different development events, I do not recommend the combination. SR is a relative value but not an absolute score for all lineages. The comparison should be restricted into certain lineage, otherwise the values will not be reflecting the biological patterns.

Best,
Weiyan

**Comment by danhtruong** [comment]
Thanks for the response. I have some single-cell data of differentiating cells. The data matched up with what we expected, low SR with more differentiated cells. 

Now, I want to compare this data to various bulk RNA-seq sets (same lineage). As I understand what you said, I should compare the output SR from both single-cell and bulk when analyzed separately. Let me know if I am on the right track or if this comparison fails due to technology.

**Comment by ChenWeiyan** [comment]
If you want to compare SR from single cell with SR from bulk sample, it will make no sense. Because bulk samples tend to have higher SR comparing to single cell samples, no matter what differentiation stages they are at.

So the comparison between less-differentiated cells and differentiated cells should be treated separately. Or you can do a matched comparison, i.e. compare SR across the same cell type/stages in both single cell and bulk samples, which we have done in our [2017 Nature Communications paper](https://www.nature.com/articles/ncomms15599).

Hope this will be helpful.

Best,
Weiyan
